services:

  messenger:
    build:
      context: ../../.
      dockerfile: ./Dockerfile
      args:
        MODE: pre-alpha
    ports:
      - "6955:80"
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

version: '3.7'
