services:

  messenger:
    build:
      context: ../../.
      dockerfile: ./Dockerfile
      args:
        MODE: pre-alpha
    ports:
      - "6955:5173"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

version: '3.7'
